This is where python exceptions will take place
